### ISSUE TITLE
Comparison with GATK's IndelRealigner?

### ISSUE THREAD

**Issue by iskandr** [mozack/abra2#17]
Has anyone looked at the impact of using ABRA2 vs. IndelRealigner in DNA variant calling? If so, can you link to that paper / blog post / repo?

**Comment by mozack** [comment]
We compared the original ABRA implementation to IndelRealigner.
See Fig. 1:
https://academic.oup.com/bioinformatics/article/30/19/2813/2422200

**Comment by iskandr** [comment]
Is the realignment method significantly different between the original implementation and ABRA2? 

Also, has anyone done any followup work using newer somatic variant callers. I'd be curious if ABRA/ABRA2 have an impact on the variant calls generated by Mutect2 (which also performs local micro-assembly).

**Comment by mozack** [comment]
We started from the original codebase, so there is a fair bit in common between the 2 versions.  There are also several key differences.

Since Mutect2 does denovo assembly on regions of interest, improved local alignments will not help much.  Rescue of unmapped reads may help a bit in some cases.  The overall impact of ABRA2 on Mutect2 is small.

In our internal testing of somatic callers, we've seen a bigger (positive) impact on Strelka2/Manta.

**Comment by mozack** [comment]
Lastly, I'll point out that there are still some cases where calls are rescued for the GATK callers such as:
https://link.springer.com/article/10.1007/s40291-017-0304-x

Closing this now - but let me know if I can clarify anything else.
